language: java
jdk:
    - oraclejdk14

services:
    - mysql

notifications:
    email: false

before_install:
    - mysql -e 'CREATE DATABASE api;'
    - mysql -e 'CREATE USER root WITH PASSWORD 'admin123';'
    - mysql -e 'GRANT ALL PRIVILEGES ON api.* TO 'root';'
    - mysql -e 'FLUSH PRIVILEGES;'
      
      