language: java
jdk:
    - oraclejdk14

services:
    - mysql

notifications:
    email: false

before_install:
    - mysql -e "CREATE DATABASE api;"
    - mysql -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin123';"
    - mysql -e "GRANT ALL PRIVILEGES ON api.* TO 'admin';"
    - mysql -e "FLUSH PRIVILEGES;"
      
      